<template>
    <select name="" id=""
        class="w-full p-4 border-[1px] border-black/[0.1] rounded-ss-lg rounded-se-lg font-[400] relative appearance-none">
        <option value="indonesia">Indonesia (+62)</option>
        <option value="93AF">Afganistan (+93)</option>
        <option value="27ZA">Afrika Selatan (+27)</option>
        <option value="355AL">Albania (+355)</option>
        <option value="213DZ">Aljazair (+213)</option>
        <option value="1US">Amerika Serikat (+1)</option>
        <option value="376AD">Andorra (+376)</option>
        <option value="244AO">Angola (+244)</option>
        <option value="1AI">Anguilla (+1)</option>
        <option value="1AG">Antigua dan Barbuda (+1)</option>
        <option value="966SA">Arab Saudi (+966)</option>
        <option value="54AR">Argentina (+54)</option>
        <option value="374AM">Armenia (+374)</option>
        <option value="297AW">Aruba (+297)</option>
        <option value="61AU">Australia (+61)</option>
        <option value="43AT">Austria (+43)</option>
        <option value="994AZ">Azerbaijan (+994)</option>
        <option value="1BS">Bahama (+1)</option>
        <option value="973BH">Bahrain (+973)</option>
        <option value="880BD">Bangladesh (+880)</option>
        <option value="1BB">Barbados (+1)</option>
        <option value="31NL">Belanda (+31)</option>
        <option value="375BY">Belarus (+375)</option>
        <option value="32BE">Belgia (+32)</option>
        <option value="501BZ">Belize (+501)</option>
        <option value="229BJ">Benin (+229)</option>
        <option value="1BM">Bermuda (+1)</option>
        <option value="975BT">Bhutan (+975)</option>
        <option value="591BO">Bolivia (+591)</option>
        <option value="599BQ">Bonaire, Sint Eustatius, dan Saba (+599)</option>
        <option value="387BA">Bosnia dan Herzegovina (+387)</option>
        <option value="267BW">Botswana (+267)</option>
        <option value="55BR">Brasil (+55)</option>
        <option value="673BN">Brunei (+673)</option>
        <option value="359BG">Bulgaria (+359)</option>
        <option value="226BF">Burkina Faso (+226)</option>
        <option value="257BI">Burundi (+257)</option>
        <option value="235TD">Cad (+235)</option>
        <option value="420CZ">Ceko (+420)</option>
        <option value="56CL">Cile (+56)</option>
        <option value="242CG">Kongo (+242)</option>
        <option value="225CI">Côte d’Ivoire (+225)</option>
        <option value="599CW">Curaçao (+599)</option>
        <option value="243CD">Republik Demokratik Kongo (+243)</option>
        <option value="45DK">Denmark (+45)</option>
        <option value="1DM">Dominika (+1)</option>
        <option value="593EC">Ekuador (+593)</option>
        <option value="503SV">El Salvador (+503)</option>
        <option value="291ER">Eritrea (+291)</option>
        <option value="372EE">Estonia (+372)</option>
        <option value="268SZ">eSwatini (+268)</option>
        <option value="251ET">Etiopia (+251)</option>
        <option value="679FJ">Fiji (+679)</option>
        <option value="63PH">Filipina (+63)</option>
        <option value="358FI">Finlandia (+358)</option>
        <option value="241GA">Gabon (+241)</option>
        <option value="220GM">Gambia (+220)</option>
        <option value="995GE">Georgia (+995)</option>
        <option value="500GS">Georgia Selatan &amp; Kep. Sandwich Selatan (+500)</option>
        <option value="233GH">Ghana (+233)</option>
        <option value="350GI">Gibraltar (+350)</option>
        <option value="1GD">Grenada (+1)</option>
        <option value="299GL">Grinlandia (+299)</option>
        <option value="590GP">Guadeloupe (+590)</option>
        <option value="1GU">Guam (+1)</option>
        <option value="502GT">Guatemala (+502)</option>
        <option value="44GG">Guernsey (+44)</option>
        <option value="224GN">Guinea (+224)</option>
        <option value="240GQ">Guinea Ekuatorial (+240)</option>
        <option value="245GW">Guinea-Bissau (+245)</option>
        <option value="592GY">Guyana (+592)</option>
        <option value="594GF">Guyana Prancis (+594)</option>
        <option value="509HT">Haiti (+509)</option>
        <option value="504HN">Honduras (+504)</option>
        <option value="852HK">Hong Kong (+852)</option>
        <option value="36HU">Hungaria (+36)</option>
        <option value="91IN">India (+91)</option>
        <option value="62ID">Indonesia (+62)</option>
        <option value="44GB">Inggris Raya (+44)</option>
        <option value="964IQ">Irak (+964)</option>
        <option value="353IE">Irlandia (+353)</option>
        <option value="354IS">Islandia (+354)</option>
        <option value="972IL">Israel (+972)</option>
        <option value="39IT">Italia (+39)</option>
        <option value="1JM">Jamaika (+1)</option>
        <option value="81JP">Jepang (+81)</option>
        <option value="49DE">Jerman (+49)</option>
        <option value="44JE">Jersey (+44)</option>
        <option value="253DJ">Jibuti (+253)</option>
        <option value="687NC">Kaledonia Baru (+687)</option>
        <option value="855KH">Kamboja (+855)</option>
        <option value="237CM">Kamerun (+237)</option>
        <option value="1CA">Kanada (+1)</option>
        <option value="7KZ">Kazakstan (+7)</option>
        <option value="254KE">Kenya (+254)</option>
        <option value="358AX">Kepulauan Aland (+358)</option>
        <option value="1KY">Kepulauan Cayman (+1)</option>
        <option value="61CC">Kepulauan Cocos (Keeling) (+61)</option>
        <option value="682CK">Kepulauan Cook (+682)</option>
        <option value="500FK">Kepulauan Falkland (+500)</option>
        <option value="298FO">Kepulauan Faroe (+298)</option>
        <option value="1MP">Kepulauan Mariana Utara (+1)</option>
        <option value="692MH">Kepulauan Marshall (+692)</option>
        <option value="672NF">Kepulauan Norfolk (+672)</option>
        <option value="64PN">Kepulauan Pitcairn (+64)</option>
        <option value="677SB">Kepulauan Solomon (+677)</option>
        <option value="47SJ">Kepulauan Svalbard dan Jan Mayen (+47)</option>
        <option value="1TC">Kepulauan Turks dan Caicos (+1)</option>
        <option value="1VI">Kepulauan Virgin Amerika Serikat (+1)</option>
        <option value="1VG">Kepulauan Virgin Britania Raya (+1)</option>
        <option value="681WF">Kepulauan Wallis dan Futuna (+681)</option>
        <option value="996KG">Kirgistan (+996)</option>
        <option value="686KI">Kiribati (+686)</option>
        <option value="57CO">Kolombia (+57)</option>
        <option value="269KM">Komoro (+269)</option>
        <option value="82KR">Korea Selatan (+82)</option>
        <option value="383XK">Kosovo (+383)</option>
        <option value="506CR">Kosta Rika (+506)</option>
        <option value="385HR">Kroasia (+385)</option>
        <option value="53CU">Kuba (+53)</option>
        <option value="965KW">Kuwait (+965)</option>
        <option value="856LA">Laos (+856)</option>
        <option value="371LV">Latvia (+371)</option>
        <option value="961LB">Lebanon (+961)</option>
        <option value="266LS">Lesotho (+266)</option>
        <option value="231LR">Liberia (+231)</option>
        <option value="218LY">Libia (+218)</option>
        <option value="423LI">Liechtenstein (+423)</option>
        <option value="370LT">Lituania (+370)</option>
        <option value="352LU">Luksemburg (+352)</option>
        <option value="853MO">Makau (+853)</option>
        <option value="389MK">Makedonia Utara (+389)</option>
        <option value="261MG">Madagaskar (+261)</option>
        <option value="960MV">Maladewa (+960)</option>
        <option value="265MW">Malawi (+265)</option>
        <option value="60MY">Malaysia (+60)</option>
        <option value="223ML">Mali (+223)</option>
        <option value="356MT">Malta (+356)</option>
        <option value="212MA">Maroko (+212)</option>
        <option value="596MQ">Martinik (+596)</option>
        <option value="222MR">Mauritania (+222)</option>
        <option value="230MU">Mauritius (+230)</option>
        <option value="262YT">Mayotte (+262)</option>
        <option value="52MX">Meksiko (+52)</option>
        <option value="20EG">Mesir (+20)</option>
        <option value="691FM">Mikronesia (+691)</option>
        <option value="373MD">Moldova (+373)</option>
        <option value="377MC">Monako (+377)</option>
        <option value="976MN">Mongolia (+976)</option>
        <option value="382ME">Montenegro (+382)</option>
        <option value="1MS">Montserrat (+1)</option>
        <option value="258MZ">Mozambik (+258)</option>
        <option value="95MM">Myanmar (Burma) (+95)</option>
        <option value="264NA">Namibia (+264)</option>
        <option value="674NR">Nauru (+674)</option>
        <option value="977NP">Nepal (+977)</option>
        <option value="227NE">Niger (+227)</option>
        <option value="234NG">Nigeria (+234)</option>
        <option value="505NI">Nikaragua (+505)</option>
        <option value="683NU">Niue (+683)</option>
        <option value="47NO">Norwegia (+47)</option>
        <option value="968OM">Oman (+968)</option>
        <option value="92PK">Pakistan (+92)</option>
        <option value="680PW">Palau (+680)</option>
        <option value="507PA">Panama (+507)</option>
        <option value="675PG">Papua Nugini (+675)</option>
        <option value="595PY">Paraguay (+595)</option>
        <option value="51PE">Peru (+51)</option>
        <option value="48PL">Polandia (+48)</option>
        <option value="689PF">Polinesia Prancis (+689)</option>
        <option value="351PT">Portugal (+351)</option>
        <option value="33FR">Prancis (+33)</option>
        <option value="1PR">Puerto Riko (+1)</option>
        <option value="44IM">Pulau Man (+44)</option>
        <option value="61CX">Pulau Natal (+61)</option>
        <option value="974QA">Qatar (+974)</option>
        <option value="236CF">Republik Afrika Tengah (+236)</option>
        <option value="1DO">Republik Dominika (+1)</option>
        <option value="262RE">Réunion (+262)</option>
        <option value="40RO">Rumania (+40)</option>
        <option value="7RU">Rusia (+7)</option>
        <option value="250RW">Rwanda (+250)</option>
        <option value="212EH">Sahara Barat (+212)</option>
        <option value="590BL">Saint Barthélemy (+590)</option>
        <option value="290SH">Saint Helena (+290)</option>
        <option value="1KN">Saint Kitts dan Nevis (+1)</option>
        <option value="1LC">Saint Lucia (+1)</option>
        <option value="590MF">Saint Martin (+590)</option>
        <option value="508PM">Saint Pierre dan Miquelon (+508)</option>
        <option value="1VC">Saint Vincent dan Grenadine (+1)</option>
        <option value="685WS">Samoa (+685)</option>
        <option value="1AS">Samoa Amerika (+1)</option>
        <option value="378SM">San Marino (+378)</option>
        <option value="239ST">Sao Tome dan Principe (+239)</option>
        <option value="64NZ">Selandia Baru (+64)</option>
        <option value="221SN">Senegal (+221)</option>
        <option value="381RS">Serbia (+381)</option>
        <option value="248SC">Seychelles (+248)</option>
        <option value="232SL">Sierra Leone (+232)</option>
        <option value="65SG">Singapura (+65)</option>
        <option value="1SX">Sint Maarten (+1)</option>
        <option value="357CY">Siprus (+357)</option>
        <option value="421SK">Slovakia (+421)</option>
        <option value="386SI">Slovenia (+386)</option>
        <option value="252SO">Somalia (+252)</option>
        <option value="34ES">Spanyol (+34)</option>
        <option value="94LK">Sri Lanka (+94)</option>
        <option value="249SD">Sudan (+249)</option>
        <option value="211SS">Sudan Selatan (+211)</option>
        <option value="597SR">Suriname (+597)</option>
        <option value="46SE">Swedia (+46)</option>
        <option value="41CH">Swiss (+41)</option>
        <option value="886TW">Taiwan (+886)</option>
        <option value="992TJ">Tajikistan (+992)</option>
        <option value="238CV">Tanjung Verde (+238)</option>
        <option value="255TZ">Tanzania (+255)</option>
        <option value="66TH">Thailand (+66)</option>
        <option value="670TL">Timor Leste (+670)</option>
        <option value="86CN">Tiongkok (+86)</option>
        <option value="228TG">Togo (+228)</option>
        <option value="690TK">Tokelau (+690)</option>
        <option value="676TO">Tonga (+676)</option>
        <option value="1TT">Trinidad dan Tobago (+1)</option>
        <option value="216TN">Tunisia (+216)</option>
        <option value="90TR">Turki (+90)</option>
        <option value="993TM">Turkimenistan (+993)</option>
        <option value="688TV">Tuvalu (+688)</option>
        <option value="256UG">Uganda (+256)</option>
        <option value="380UA">Ukraina (+380)</option>
        <option value="971AE">Uni Emirat Arab (+971)</option>
        <option value="598UY">Uruguay (+598)</option>
        <option value="998UZ">Uzbekistan (+998)</option>
        <option value="678VU">Vanuatu (+678)</option>
        <option value="379VA">Vatikan (+379)</option>
        <option value="58VE">Venezuela (+58)</option>
        <option value="84VN">Vietnam (+84)</option>
        <option value="246IO">Wilayah Inggris di Samudra Hindia (+246)</option>
        <option value="970PS">Wilayah Palestina (+970)</option>
        <option value="967YE">Yaman (+967)</option>
        <option value="962JO">Yordania (+962)</option>
        <option value="30GR">Yunani (+30)</option>
        <option value="260ZM">Zambia (+260)</option>
        <option value="263ZW">Zimbabwe (+263)</option>
    </select>
</template>